//! Dynamic Routing
// import "./globals.css";

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       {/* Ignores warning -> I know there’s a mismatch in this part of the DOM. It’s expected. Don’t warn me about it. */}
//       {/* <body suppressHydrationWarning> */}
//       <body>
//         {children}
//       </body>
//     </html>
//   );
// }

//! ===========================================================================

//! Sharing variable between components (BAD METHOD)
// import "./globals.css";

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body>
//           {children}
//       </body>
//     </html>
//   );
// }

//! ===========================================================================

// ! Context API
//todo IMPORTANT -> don't use curly braces here in "MyContext"
// import  MyContext  from "@/Helper/Context";
// import "./globals.css";

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body suppressHydrationWarning>
//         <MyContext>
//           {children}
//         </MyContext>
//       </body>
//     </html>
//   );
// }

//! ===========================================================================

//! React Toastify
// import "./globals.css";

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body>
//           {children}
//       </body>
//     </html>
//   );
// }